language: node_js
node_js:
  - "14.15.3"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install
script:
  - npm run lint
  - npm run build-aot
  #  - TODO: remove include
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --include="packages/components"
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox --include="packages/dynamic"
